# Generated by Django 2.2 on 2019-07-29 15:50

from django.db import migrations, models
import gray_merchant.utils
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('gray_merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='address line 1'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[gray_merchant.utils.ZipCodeValidator], verbose_name='zip code'),
        ),
    ]
