# Generated by Django 2.2 on 2019-06-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gray_merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
