# Generated by Django 2.2 on 2019-07-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gray_merchant', '0002_auto_20190729_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
