# Generated by Django 2.2 on 2019-04-11 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_transaction',
            field=models.ForeignKey(blank=True, help_text='Purchase transaction in which item was acquired', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='transactions.Purchase'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sale_transaction',
            field=models.ForeignKey(blank=True, help_text='Sale transaction in which item was sold', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='transactions.Sale'),
        ),
    ]
