# Generated by Django 2.2 on 2019-04-15 02:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gray_merchant', '0002_auto_20190415_0252'),
        ('inventory', '0002_auto_20190411_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingdetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='id',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gray_merchant.Vendor'),
        ),
        migrations.AlterField(
            model_name='gradingdetails',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
