# Generated by Django 2.2 on 2019-04-11 00:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('card_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 4, 11, 0, 28, 1, 668965))),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('store_credit', 'Store Credit'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal')], max_length=32)),
                ('transaction_total', models.FloatField(help_text='Total amount of transaction.')),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('notes', models.TextField()),
                ('captured_price', models.ForeignKey(help_text='Most recent price synced for item at time of transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='card_catalog.CardPrice')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem')),
            ],
            options={
                'verbose_name': 'transaction_item',
                'verbose_name_plural': 'transaction_items',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('basetransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.BaseTransaction')),
                ('sold_items', models.ManyToManyField(related_name='sold_items', to='transactions.TransactionItem')),
            ],
            options={
                'verbose_name': 'sale_transactions',
                'verbose_name_plural': 'sale_transactions',
            },
            bases=('transactions.basetransaction',),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('basetransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.BaseTransaction')),
                ('buylist_items', models.ManyToManyField(related_name='buylist_items', to='transactions.TransactionItem')),
            ],
            options={
                'verbose_name': 'purchase_transaction',
                'verbose_name_plural': 'purchase_transactions',
            },
            bases=('transactions.basetransaction',),
        ),
    ]
