# Generated by Django 2.2 on 2019-04-15 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gray_merchant', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetransaction',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gray_merchant.Vendor'),
        ),
        migrations.AlterField(
            model_name='basetransaction',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('store_credit', 'Store Credit'), ('store_credit', 'Store Credit'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal')], max_length=32),
        ),
        migrations.AlterField(
            model_name='basetransaction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
