# Generated by Django 2.2 on 2019-04-15 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190415_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetransaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='basetransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
